WITH CTE AS (

SELECT 
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

{{weekend_checker('STARTED_AT')}},

{{season_checker('STARTED_AT')}}

FROM
{{ source('demo', 'bike') }}
WHERE STARTED_AT <> 'started_at'

)

SELECT * FROM CTE
