WITH TRIPS AS (
    SELECT 
    RIDE_ID,
    RIDEABLE_TYPE,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS Trip_Date,
    start_statio_id AS START_STATION_ID,
    END_STATION_ID,
    MEMBER_CSUAL AS MEMBER_CASUAL,
    TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT) , TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS
    FROM {{ source('demo', 'bike') }}
    WHERE RIDE_ID <> 'ride_id'
    LIMIT 10
)

SELECT *
FROM TRIPS